name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  hetu_script: ^0.4.2+1
  hetu_std:
    path: ../../hetu_std
  hetu_spotify_gql_api_client:
    path: ../
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
