name: hetu_spotify_gql_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  hetu_script: ^0.4.2+1
  hetu_std:
    git:
      url: https://github.com/hetu-community/hetu_std.git
  path: ^1.9.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
